POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "Pudzian",
"number": "222-242-213"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "Pudzianooo",
"number": "222242213"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
"number": "222-242-213"
}